### ISSUE TITLE
Problems with Puppet Agent v5.3.3

### ISSUE THREAD

**Issue by TraGicCode** [voxpupuli/ra10ke#11]
When running rake r10k:syntax with the puppet agent 5.3.3 gem i get the following error.

```
➜  gcc-inf git:(development) bundle exec rake r10k:syntax
rake aborted!
NoMethodError: undefined method `map' for true:TrueClass
Did you mean?  tap
/Users/michealfyffe/Source/GitHub/gcc-cm/gcc-inf/.bundle/ruby/2.4.0/gems/fast_gettext-1.1.0/lib/fast_gettext/storage.rb:31:in `available_locales'
/Users/michealfyffe/Source/GitHub/gcc-cm/gcc-inf/.bundle/ruby/2.4.0/gems/fast_gettext-1.1.0/lib/fast_gettext/storage.rb:132:in `block in best_locale_in'
/Users/michealfyffe/Source/GitHub/gcc-cm/gcc-inf/.bundle/ruby/2.4.0/gems/fast_gettext-1.1.0/lib/fast_gettext/storage.rb:131:in `each'
/Users/michealfyffe/Source/GitHub/gcc-cm/gcc-inf/.bundle/ruby/2.4.0/gems/fast_gettext-1.1.0/lib/fast_gettext/storage.rb:131:in `best_locale_in'
/Users/michealfyffe/Source/GitHub/gcc-cm/gcc-inf/.bundle/ruby/2.4.0/gems/fast_gettext-1.1.0/lib/fast_gettext/storage.rb:111:in `set_locale'
/Users/michealfyffe/Source/GitHub/gcc-cm/gcc-inf/.bundle/ruby/2.4.0/gems/fast_gettext-1.1.0/lib/fast_gettext/storage.rb:104:in `locale='
/Users/michealfyffe/Source/GitHub/gcc-cm/gcc-inf/.bundle/ruby/2.4.0/gems/r10k-2.6.1/lib/r10k.rb:7:in `<module:R10K>'
/Users/michealfyffe/Source/GitHub/gcc-cm/gcc-inf/.bundle/ruby/2.4.0/gems/r10k-2.6.1/lib/r10k.rb:3:in `<top (required)>'
/Users/michealfyffe/Source/GitHub/gcc-cm/gcc-inf/.bundle/ruby/2.4.0/gems/r10k-2.6.1/lib/r10k/module.rb:1:in `require'
/Users/michealfyffe/Source/GitHub/gcc-cm/gcc-inf/.bundle/ruby/2.4.0/gems/r10k-2.6.1/lib/r10k/module.rb:1:in `<top (required)>'
/Users/michealfyffe/Source/GitHub/gcc-cm/gcc-inf/.bundle/ruby/2.4.0/gems/r10k-2.6.1/lib/r10k/puppetfile.rb:2:in `require'
/Users/michealfyffe/Source/GitHub/gcc-cm/gcc-inf/.bundle/ruby/2.4.0/gems/r10k-2.6.1/lib/r10k/puppetfile.rb:2:in `<top (required)>'
/Users/michealfyffe/Source/GitHub/gcc-cm/gcc-inf/.bundle/ruby/2.4.0/gems/r10k-2.6.1/lib/r10k/action/puppetfile/check.rb:1:in `require'
/Users/michealfyffe/Source/GitHub/gcc-cm/gcc-inf/.bundle/ruby/2.4.0/gems/r10k-2.6.1/lib/r10k/action/puppetfile/check.rb:1:in `<top (required)>'
/Users/michealfyffe/Source/GitHub/gcc-cm/gcc-inf/.bundle/ruby/2.4.0/gems/ra10ke-0.3.0/lib/ra10ke.rb:76:in `require'
/Users/michealfyffe/Source/GitHub/gcc-cm/gcc-inf/.bundle/ruby/2.4.0/gems/ra10ke-0.3.0/lib/ra10ke.rb:76:in `block (2 levels) in initialize'
/Users/michealfyffe/Source/GitHub/gcc-cm/gcc-inf/.bundle/ruby/2.4.0/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
/Users/michealfyffe/.rvm/gems/ruby-2.4.2/bin/bundle:23:in `load'
/Users/michealfyffe/.rvm/gems/ruby-2.4.2/bin/bundle:23:in `<main>'
/Users/michealfyffe/.rvm/gems/ruby-2.4.2/bin/ruby_executable_hooks:15:in `eval'
/Users/michealfyffe/.rvm/gems/ruby-2.4.2/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => r10k:syntax
(See full trace by running task with --trace)
```

GemFile
```ruby
source ENV['GEM_SOURCE'] || 'https://rubygems.org'

gem 'facter', '>= 1.7.0'
gem 'guard-rake'
gem 'metadata-json-lint'
gem 'puppet', ENV['PUPPET_GEM_VERSION'] || '= 5.3.3'
gem 'puppet-lint', '>= 1.0.0'
gem 'puppet-strings'
gem 'puppetlabs_spec_helper', '>= 1.0.0'
gem 'rspec-puppet'
gem 'hiera-eyaml'

gem 'beaker'
gem 'beaker-puppet_install_helper'
gem 'beaker-rspec'
gem 'serverspec'
gem 'winrm'

gem 'rake'
gem 'rubocop'
gem 'rubocop-rspec'

gem 'generate-puppetfile'
gem 'ra10ke', '>= 0.3.0'
gem 'r10k', '>= 2.5.5'

# Debugging
gem 'pry'                # Pry Debugger: Consle driven debugger.  Stops the execution in the middle of a call to allow inspection of ruby variables
gem 'pry-byebug'         # Pry Plugin: used to step through the code
gem 'pry-stack_explorer' # Pry Plugin: used to step through the code.  Shows how you got to where you are now and the variables at each point in the stack
gem 'pry-rescue'         # Pry Plugin: used to automatically break in a pry session when an exception is being thrown
```

The solution was downgrading puppet to 5.3.2 like so

GemFile
```ruby
source ENV['GEM_SOURCE'] || 'https://rubygems.org'

gem 'facter', '>= 1.7.0'
gem 'guard-rake'
gem 'metadata-json-lint'
gem 'puppet', ENV['PUPPET_GEM_VERSION'] || '= 5.3.2'
gem 'puppet-lint', '>= 1.0.0'
gem 'puppet-strings'
gem 'puppetlabs_spec_helper', '>= 1.0.0'
gem 'rspec-puppet'
gem 'hiera-eyaml'

gem 'beaker'
gem 'beaker-puppet_install_helper'
gem 'beaker-rspec'
gem 'serverspec'
gem 'winrm'

gem 'rake'
gem 'rubocop'
gem 'rubocop-rspec'

gem 'generate-puppetfile'
gem 'ra10ke', '>= 0.3.0'
gem 'r10k', '>= 2.5.5'
```

Sounds like this should be on the radar for getting fixed/resolved.

**Comment by sigv** [comment]
It looks like some expectations in some dependencies have been violated. Before digging deeper - can you please confirm whether this is still an issue for you with `puppet = 5.4.0` and all your other gems being up to date?

**Comment by TraGicCode** [comment]
Did a bundle update and everything seems to be working even with 5.3.3.  Closing this.
