### ISSUE TITLE
Breaks for Puppetfile path '.'

### ISSUE THREAD

**Issue by baurmatt** [voxpupuli/ra10ke#18]
```
mbaur(2018-04-06 16:55:11)  ~/Sources/syseleven-control  (pp-4938)
$ rake r10k:dependencies
rake aborted!
R10K::Error: Puppetfile cannot manage content 'base' outside of containing environment: modules is not within .
/Users/mbaur/.rvm/gems/ruby-2.4.3@ra10ke/gems/r10k-2.6.2/lib/r10k/puppetfile.rb:179:in `validate_install_path'
/Users/mbaur/.rvm/gems/ruby-2.4.3@ra10ke/gems/r10k-2.6.2/lib/r10k/puppetfile.rb:105:in `add_module'
/Users/mbaur/.rvm/gems/ruby-2.4.3@ra10ke/gems/r10k-2.6.2/lib/r10k/puppetfile.rb:195:in `mod'
./Puppetfile:2:in `load!'
/Users/mbaur/.rvm/gems/ruby-2.4.3@ra10ke/gems/r10k-2.6.2/lib/r10k/puppetfile.rb:68:in `instance_eval'
/Users/mbaur/.rvm/gems/ruby-2.4.3@ra10ke/gems/r10k-2.6.2/lib/r10k/puppetfile.rb:68:in `load!'
/Users/mbaur/.rvm/gems/ruby-2.4.3@ra10ke/gems/ra10ke-0.3.0/lib/ra10ke.rb:18:in `block (2 levels) in initialize'
/Users/mbaur/.rvm/gems/ruby-2.4.3@global/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => r10k:dependencies
(See full trace by running task with --trace)
```

Comparing with r10k's use of `R10K::Puppetfile.new()`, the difference seems to be that r10k usually expects a absolute path.

**Comment by sigv** [comment]
For a minimal Puppetfile to reproduce the issue:

```ruby
forge 'https://forgeapi.puppetlabs.com'

mod 'puppetlabs-stdlib',
  :git => 'git@github.com:puppetlabs/puppetlabs-stdlib.git',
  :tag => '4.25.0',
  :install_path => 'external'
```
