### ISSUE TITLE
Support :control_branch 

### ISSUE THREAD

**Issue by baurmatt** [voxpupuli/ra10ke#20]
As of r10k 2.4.0 branch can be set to :control_branch. This breaks ra10ke with:

```
mbaur(2018-04-06 17:00:46)  ~/Sources/syseleven-control  (pp-4938)
$ rake r10k:dependencies
rake aborted!
Unable to determine ref_type for private
/Users/mbaur/.rvm/gems/ruby-2.4.3@ra10ke/gems/ra10ke-0.3.0/lib/ra10ke.rb:66:in `block (3 levels) in initialize'
/Users/mbaur/.rvm/gems/ruby-2.4.3@ra10ke/gems/ra10ke-0.3.0/lib/ra10ke.rb:26:in `each'
/Users/mbaur/.rvm/gems/ruby-2.4.3@ra10ke/gems/ra10ke-0.3.0/lib/ra10ke.rb:26:in `block (2 levels) in initialize'
/Users/mbaur/.rvm/gems/ruby-2.4.3@global/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => r10k:dependencies
(See full trace by running task with --trace)
```

https://github.com/puppetlabs/r10k/blob/master/doc/puppetfile.mkd#control-repo-branch-tracking

**Comment by baurmatt** [comment]
Ah, this was already fixed with d967382b086f9a3f7f61f5c7c111a8a04600aa9c but not released as gem. Opening another issue for that ;)
