### ISSUE TITLE
r10k:dependencies 'NoMethodError: undefined method `each' for true:TrueClass'

### ISSUE THREAD

**Issue by ryayon** [voxpupuli/ra10ke#5]
Hi,

I get the following error with r10k 2.5.1 and ra10ke 0.1.1:

```bash
+ bundle exec rake r10k:dependencies --trace
** Invoke r10k:dependencies (first_time)
** Execute r10k:dependencies
rake aborted!
NoMethodError: undefined method `each' for true:TrueClass
/home/jenkins/workspace/puppet-r10k_production-MZMJAVYNZFZSN43RSNC7VNXLV4PMWG5QN47VHVMJP2CU7OBU664Q/vendor/ruby/2.3.0/gems/ra10ke-0.1.1/lib/ra10ke.rb:17:in `block (2 levels) in initialize'
/home/jenkins/workspace/puppet-r10k_production-MZMJAVYNZFZSN43RSNC7VNXLV4PMWG5QN47VHVMJP2CU7OBU664Q/vendor/ruby/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `block in execute'
/home/jenkins/workspace/puppet-r10k_production-MZMJAVYNZFZSN43RSNC7VNXLV4PMWG5QN47VHVMJP2CU7OBU664Q/vendor/ruby/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `each'
/home/jenkins/workspace/puppet-r10k_production-MZMJAVYNZFZSN43RSNC7VNXLV4PMWG5QN47VHVMJP2CU7OBU664Q/vendor/ruby/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
/home/jenkins/workspace/puppet-r10k_production-MZMJAVYNZFZSN43RSNC7VNXLV4PMWG5QN47VHVMJP2CU7OBU664Q/vendor/ruby/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/home/jenkins/workspace/puppet-r10k_production-MZMJAVYNZFZSN43RSNC7VNXLV4PMWG5QN47VHVMJP2CU7OBU664Q/vendor/ruby/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
/home/jenkins/workspace/puppet-r10k_production-MZMJAVYNZFZSN43RSNC7VNXLV4PMWG5QN47VHVMJP2CU7OBU664Q/vendor/ruby/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:180:in `invoke'
/home/jenkins/workspace/puppet-r10k_production-MZMJAVYNZFZSN43RSNC7VNXLV4PMWG5QN47VHVMJP2CU7OBU664Q/vendor/ruby/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:152:in `invoke_task'
/home/jenkins/workspace/puppet-r10k_production-MZMJAVYNZFZSN43RSNC7VNXLV4PMWG5QN47VHVMJP2CU7OBU664Q/vendor/ruby/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'
/home/jenkins/workspace/puppet-r10k_production-MZMJAVYNZFZSN43RSNC7VNXLV4PMWG5QN47VHVMJP2CU7OBU664Q/vendor/ruby/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `each'
/home/jenkins/workspace/puppet-r10k_production-MZMJAVYNZFZSN43RSNC7VNXLV4PMWG5QN47VHVMJP2CU7OBU664Q/vendor/ruby/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `block in top_level'
/home/jenkins/workspace/puppet-r10k_production-MZMJAVYNZFZSN43RSNC7VNXLV4PMWG5QN47VHVMJP2CU7OBU664Q/vendor/ruby/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:117:in `run_with_threads'
/home/jenkins/workspace/puppet-r10k_production-MZMJAVYNZFZSN43RSNC7VNXLV4PMWG5QN47VHVMJP2CU7OBU664Q/vendor/ruby/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:102:in `top_level'
/home/jenkins/workspace/puppet-r10k_production-MZMJAVYNZFZSN43RSNC7VNXLV4PMWG5QN47VHVMJP2CU7OBU664Q/vendor/ruby/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:80:in `block in run'
/home/jenkins/workspace/puppet-r10k_production-MZMJAVYNZFZSN43RSNC7VNXLV4PMWG5QN47VHVMJP2CU7OBU664Q/vendor/ruby/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
/home/jenkins/workspace/puppet-r10k_production-MZMJAVYNZFZSN43RSNC7VNXLV4PMWG5QN47VHVMJP2CU7OBU664Q/vendor/ruby/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:77:in `run'
/home/jenkins/workspace/puppet-r10k_production-MZMJAVYNZFZSN43RSNC7VNXLV4PMWG5QN47VHVMJP2CU7OBU664Q/vendor/ruby/2.3.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/home/jenkins/workspace/puppet-r10k_production-MZMJAVYNZFZSN43RSNC7VNXLV4PMWG5QN47VHVMJP2CU7OBU664Q/vendor/ruby/2.3.0/bin/rake:23:in `load'
/home/jenkins/workspace/puppet-r10k_production-MZMJAVYNZFZSN43RSNC7VNXLV4PMWG5QN47VHVMJP2CU7OBU664Q/vendor/ruby/2.3.0/bin/rake:23:in `<top (required)>'
/usr/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:74:in `load'
/usr/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:74:in `kernel_load'
/usr/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:27:in `run'
/usr/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli.rb:332:in `exec'
/usr/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/usr/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/usr/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli.rb:20:in `dispatch'
/usr/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/usr/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli.rb:11:in `start'
/usr/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/exe/bundle:34:in `block in <top (required)>'
/usr/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
/usr/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/exe/bundle:26:in `<top (required)>'
/usr/bin/bundle:23:in `load'
/usr/bin/bundle:23:in `<main>'
Tasks: TOP => r10k:dependencies
```

Any idea?

**Comment by binford2k** [comment]
Probably corrected in https://github.com/voxpupuli/ra10ke/commit/9cc52c73cfc36cff165031d7b96bce5bcda040b7, though a backwards compatible solution would likely be better.

**Comment by walterheck** [comment]
I can confirm that if I patch my lib/ra10ke.rb with the changes in #9cc52c7 the problem goes away. Can we get that released asap please?

**Comment by tampakrap** [comment]
I will release it today. It is backwards compatible, see #3

**Comment by tampakrap** [comment]
released, enjoy. Let me know please if you have further issues

**Comment by ryayon** [comment]
I can confirm it works now.
Well done.
