### ISSUE TITLE
incompatible with r10k gem > 3.8

### ISSUE THREAD

**Issue by TheMeier** [voxpupuli/ra10ke#57]
When r10k gem 3.9 is used the following error occurs:

```
rake aborted!
ArgumentError: wrong number of arguments (given 5, expected 1..3)
/home/foo/puppet/vendor/bundle/ruby/3.0.0/gems/r10k-1.1.4/lib/r10k/puppetfile.rb:33:in `initialize'
/home/foo/puppet/vendor/bundle/ruby/3.0.0/gems/ra10ke-1.0.0/lib/ra10ke.rb:45:in `new'
/home/foo/puppet/vendor/bundle/ruby/3.0.0/gems/ra10ke-1.0.0/lib/ra10ke.rb:45:in `get_puppetfile'
/home/foo/puppet/vendor/bundle/ruby/3.0.0/gems/ra10ke-1.0.0/lib/ra10ke/dependencies.rb:9:in `block in define_task_dependencies'
/home/foo/puppet/vendor/bundle/ruby/3.0.0/gems/rake-13.0.3/exe/rake:27:in `<top (required)>'
/usr/share/gems/gems/bundler-2.2.15/lib/bundler/cli/exec.rb:63:in `load'
/usr/share/gems/gems/bundler-2.2.15/lib/bundler/cli/exec.rb:63:in `kernel_load'
/usr/share/gems/gems/bundler-2.2.15/lib/bundler/cli/exec.rb:28:in `run'
/usr/share/gems/gems/bundler-2.2.15/lib/bundler/cli.rb:494:in `exec'
/usr/share/gems/gems/bundler-2.2.15/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/share/gems/gems/bundler-2.2.15/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/usr/share/gems/gems/bundler-2.2.15/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/usr/share/gems/gems/bundler-2.2.15/lib/bundler/cli.rb:30:in `dispatch'
/usr/share/gems/gems/bundler-2.2.15/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/usr/share/gems/gems/bundler-2.2.15/lib/bundler/cli.rb:24:in `start'
/usr/share/gems/gems/bundler-2.2.15/libexec/bundle:49:in `block in <top (required)>'
/usr/share/gems/gems/bundler-2.2.15/lib/bundler/friendly_errors.rb:130:in `with_friendly_errors'
/usr/share/gems/gems/bundler-2.2.15/libexec/bundle:37:in `<top (required)>'
/home/foo/bin/bundle:23:in `load'
/home/foo/bin/bundle:23:in `<main>'
Tasks: TOP => r10k:dependencies
(See full trace by running task with --trace)
```

**Comment by ananace** [comment]
The log you have there actually mentions the r10k gem being version 1.1.4, which should work since 47b1f336fb26b1bdf00b50fe9e02c5110693634a

**Comment by logicminds** [comment]
I have pinned to r10k version 2.6 in #72 to fix this.  Issue is due to r10k gem dependency.
