### ISSUE TITLE
module with https + token is failing

### ISSUE THREAD

**Issue by rwaffen** [voxpupuli/ra10ke#84]
`bundle exec rake r10k:dependencies` is giving me the following output:

```bash
#<Thread:0x00007f91195ee028 /Users/rwaffen/Development/betadots/Kunden/puppet-control-repo/vendor/bundle/ruby/2.7.0/gems/ra10ke-2.0.0/lib/ra10ke/dependencies.rb:63 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	6: from /Users/rwaffen/Development/betadots/Kunden/puppet-control-repo/vendor/bundle/ruby/2.7.0/gems/ra10ke-2.0.0/lib/ra10ke/dependencies.rb:85:in `block (2 levels) in processed_modules'
	5: from /Users/rwaffen/Development/betadots/Kunden/puppet-control-repo/vendor/bundle/ruby/2.7.0/gems/git-1.14.0/lib/git.rb:275:in `ls_remote'
	4: from /Users/rwaffen/Development/betadots/Kunden/puppet-control-repo/vendor/bundle/ruby/2.7.0/gems/git-1.14.0/lib/git/lib.rb:505:in `ls_remote'
	3: from /Users/rwaffen/Development/betadots/Kunden/puppet-control-repo/vendor/bundle/ruby/2.7.0/gems/git-1.14.0/lib/git/lib.rb:505:in `tap'
	2: from /Users/rwaffen/Development/betadots/Kunden/puppet-control-repo/vendor/bundle/ruby/2.7.0/gems/git-1.14.0/lib/git/lib.rb:506:in `block in ls_remote'
	1: from /Users/rwaffen/Development/betadots/Kunden/puppet-control-repo/vendor/bundle/ruby/2.7.0/gems/git-1.14.0/lib/git/lib.rb:506:in `each'
/Users/rwaffen/Development/betadots/Kunden/puppet-control-repo/vendor/bundle/ruby/2.7.0/gems/git-1.14.0/lib/git/lib.rb:508:in `block (2 levels) in ls_remote': undefined method `split' for nil:NilClass (NoMethodError)
rake aborted!
NoMethodError: undefined method `split' for nil:NilClass
/Users/rwaffen/Development/betadots/Kunden/puppet-control-repo/vendor/bundle/ruby/2.7.0/gems/git-1.14.0/lib/git/lib.rb:508:in `block (2 levels) in ls_remote'
/Users/rwaffen/Development/betadots/Kunden/puppet-control-repo/vendor/bundle/ruby/2.7.0/gems/git-1.14.0/lib/git/lib.rb:506:in `each'
/Users/rwaffen/Development/betadots/Kunden/puppet-control-repo/vendor/bundle/ruby/2.7.0/gems/git-1.14.0/lib/git/lib.rb:506:in `block in ls_remote'
/Users/rwaffen/Development/betadots/Kunden/puppet-control-repo/vendor/bundle/ruby/2.7.0/gems/git-1.14.0/lib/git/lib.rb:505:in `tap'
/Users/rwaffen/Development/betadots/Kunden/puppet-control-repo/vendor/bundle/ruby/2.7.0/gems/git-1.14.0/lib/git/lib.rb:505:in `ls_remote'
/Users/rwaffen/Development/betadots/Kunden/puppet-control-repo/vendor/bundle/ruby/2.7.0/gems/git-1.14.0/lib/git.rb:275:in `ls_remote'
/Users/rwaffen/Development/betadots/Kunden/puppet-control-repo/vendor/bundle/ruby/2.7.0/gems/ra10ke-2.0.0/lib/ra10ke/dependencies.rb:85:in `block (2 levels) in processed_modules'
Tasks: TOP => r10k:dependencies
(See full trace by running task with --trace)
```

in my Puppetfile if have a module like this:

```ruby
mod 'someone-my_module',
    git: 'https://gitlab+token-name:th3_t0k3N@gitlab.example.com/puppet-modules/my_module',
    branch: 'main'
```

if i comment this out, everything works as expected.
is there something wrong with my declaration? 

the clone-url is okay and does work like this. with normal git and also with r10k checking out my modules on the puppetserver.

**Comment by drz9** [comment]
I am having a similar issue but the other way around. My puppetfile does point to a private hosted gitlab Repo but I didnt provide credentials directly in the Puppetfile. with r10k I worked around creating a ~/.git-credentials on the root User so I dont have credentials in the code. However, this does not seem to work with r10k:dependencies. Looks like credentials are not used by git gem

**Comment by drz9** [comment]
@rwaffen I traced this down a little bit and found this issue in the git library:

https://github.com/ruby-git/ruby-git/issues/516

It looks like, the git library fails when stderr isn't empty. For me it was, because the git ls-remote <httpspath> command threw a warning "redirecting to <httpspath>.git". So when I am adding .git to my https path, the r10k:dependency task works as expected. Issue is to be fixed by git library rather than ra10ke.

**Comment by rwaffen** [comment]
oh thx, will look if this also solves this for me

**Comment by rwaffen** [comment]
yeah, nice, this also fixed it for me. i have other https-repos without the `.git` and that's not a problem. only the private gitlab with token does break it if one omits this.
